inhibit_all_warnings!
use_frameworks!

target 'CubeRunner' do
    pod 'Cartography', :git => "https://github.com/robb/Cartography.git", :tag => '0.6.0'
    pod 'HTPressableButton', '~> 1.3.2'
    pod 'BitwiseFont', '~> 0.1.0'
	pod 'SwiftCubicSpline', '~> 0.1.0'
	pod 'SIAlertView', '~> 1.3'
end
