use_frameworks!
inhibit_all_warnings!

target 'ASAP' do
    pod 'SwiftyJSON', '~> 2.3.0'
    pod 'SDWebImage', '~> 3.7.3'
    pod 'FontAwesomeKit', :git => 'https://github.com/gscalzo/FontAwesomeKit'
    pod 'BBBadgeBarButtonItem', '~> 1.2'
    pod 'LatoFont', :git => "https://github.com/gscalzo/LatoFont.git"
end

