# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
use_frameworks!
inhibit_all_warnings!

target 'PrettyWeatherApp' do
    pod 'Cartography', :git => "https://github.com/robb/Cartography.git", :tag => '0.6.0'
    pod 'Alamofire', '~> 2.0'
    pod 'SwiftyJSON', '~> 2.3.0'
    pod 'WeatherIconsKit', :git => 'git@github.com:gscalzo/WeatherIconsKit.git'
    pod 'FlickrKit', '~> 1.0.5'
    pod 'FXBlurView', '~> 1.6.4'
    pod 'LatoFont', :git => "https://github.com/gscalzo/LatoFont.git"
end

